In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

<p> Yes, There is a Difference </p>

In [2]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [3]:
print('DataType of list_')
for item in list_:
    print(type(item)) 
print('DataType of array_list')
for item in array_list:
    print(type(item))  

DataType of list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
DataType of array_list
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
<pre>
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list) </pre>

<b><i> Yes, there will be a difference in the data type of the elements present in both the variables, list_ and array_list. The elements in the variable "list_" are strings, while the elements in the variable "array_list" will be converted to integers due to the dtype=int</i><b>

In [4]:
array_list = np.array(object = list_, dtype = int)
print('DataType of list_')
for item in list_:
    print(type(item)) 
print('DataType of array_list')
for item in array_list:
    print(type(item))  

DataType of list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
DataType of array_list
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Q4. Write a code to find the following characteristics of variable, num_array:
<pre>
(i) shape
(ii) size
</pre>

In [5]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print(num_array.shape)  
print(num_array.size)

(2, 3)
6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [6]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [7]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
